all:
	g++ decoder_test.cpp decoder.cpp -o decoder
	g++ stringdecoder_test.cpp stringdecoder.cpp -o stringdecoder
	
decoder:
	g++ decoder_test.cpp decoder.cpp -o decoder
	
stringdecoder:
	g++ stringdecoder_test.cpp stringdecoder.cpp -o stringdecoder
	
generaltest:

	g++ generaltest.cpp stringdecoder.cpp decoder.cpp -o generaltest
	